name: build and push nquakesv container image
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - docker-compose.yaml
      - '*.md'
      - LICENSE

env:
  REGISTRY: docker.io
  DH_NAMESPACE: ${{ secrets.DH_NAMESPACE }}
  DH_TOKEN: ${{ secrets.DH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ env.DH_NAMESPACE }}
          password: ${{ env.DH_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.DH_NAMESPACE}}/nquakesv:latest
            ${{ env.REGISTRY }}/${{ env.DH_NAMESPACE}}/nquakesv:${{ github.sha }}
